app:
  name: 'online-media-service'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'online-media-service'

postgres:
  pool_max: 2
  pg_url: 'postgres://postgres:root@localhost:5432/media_db'
