basePath: /v1
definitions:
  entity.File:
    properties:
      file_key:
        example: 0b4a4e6e-e502-454f-a8a0-fb7d445e5efa
        type: string
      file_name:
        example: template.png
        type: string
      file_url:
        example: https://example.com/images/template.png
        type: string
    type: object
  v1.removeResponse:
    properties:
      message:
        example: success
        type: string
    required:
    - message
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a file service as an example
  title: Go Media Service API
  version: "1.0"
paths:
  /file/remove/{url}:
    delete:
      consumes:
      - application/json
      description: Remove a file
      operationId: url
      parameters:
      - description: File URL
        in: path
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.removeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Remove
      tags:
      - file
  /file/store:
    post:
      consumes:
      - multipart/form-data
      description: Save file
      parameters:
      - description: Send file
        in: formData
        name: request
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.File'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Store
      tags:
      - file
swagger: "2.0"
